# DOTNET DOES NOT RUN YET
trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  solution: Project Code
  angular: Trader-App

stages: 
- stage: Restores
  #Runs NuGet and NPM restores
  jobs:
    - job: NuRestore
      displayName: NuGet Restore
      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
    - job: npmRestore
      displayName: NPM Restore
      steps:
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(angular)'

- stage: Prepare
#Prepare the sonar cloud
  jobs:
    - job: Prepare
      displayName: 'Prepare analysis configuration'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'P2 Scanner'
          organization: '210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: '210726-wvu-net-ext_Group3-P2'
          projectName: 'Group3-P2'
          extraProperties: 'sonar.exclusions=**/lib/**/*'

- stage: Builds
  #Building and Testing
  jobs:
  # Angular Build and Test Here
    - job: NGBuild 
      displayName: Angular Build/Test
      steps:
      - script: ng build
        displayName: Angular Build

      - script: ng test
        displayName: Angular Test
  # DotNet Build and Test Here
    - job: DNBuild
      displayName: Dotnet Build/Test
      steps:
      # Force dotnet 5
      - task: UseDotNet@2
        displayName: Dotnet SDK 5
        inputs:
          packageType: 'sdk'
          version: '5.x'
    
      - script: dotnet build --configuration Release
        displayName: dotnet build
        workingDirectory: $(solution)

      - script: dotnet test --configuration Release
        displayName: dotnet test
        workingDirectory: $(solution)


- stage: Final
  #Performs the Sonar Analyze and publish results
  jobs:
    - job: Analyze
      steps:
      - task: SonarCloudAnalyze@1
        displayName: 'Run SonarCloud analysis'
    - job: Publish
      steps:
      - task: SonarCloudPublish@1
        displayName: 'Publish results on build summary'