# DOES NOT RUN YET
trigger:
- main

pr:
- main

pool:
  vmImage: windows-latest

variables: #Path to folder with .sln
  solution: Project Code
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages: 
- stage: prepare
  jobs:
    - job: prepare
      steps:
      - task: SonarCloudPrepare@1
        displayName: 'Prepare analysis configuration'
        inputs:
          SonarCloud: 'P1 Scanner'
          organization: '210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: '210726-wvu-net-ext_P1-Emery-Hart'
          projectName: 'P1-Emery-Hart'
          extraProperties: 'sonar.exclusions=**/lib/**/*'

- stage: build
  jobs:
  - job: build
    
    steps:
    - task: UseDotNet@2
      displayName: Dotnet SDK 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    
    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: $(solution)

    - script: dotnet test --configuration Release
      displayName: dotnet test
      workingDirectory: $(solution)