#ANGULAR LINT NOT FULLY IMPLEMENTED YET
trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  sDir: 'P2-Store'
  solution: 'P2-Store/*.sln'
  angular: 'Trader-app'

stages: 
- stage: Installs
  #Runs NuGet and NPM Installs
  jobs:
    - job: NuInstall
      displayName: NuGet Install-Restore
      steps:
      #Install
      - task: NuGetToolInstaller@1
        inputs:
          checkLatest: true
      #Restore
      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(solution)
    - job: npmInstall
      displayName: NPM Install
      steps:
      #Install Node
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
            versionSpec: 14.x
      #Install Angular
      - task: Npm@1
        displayName: Install Angular
        inputs:
          command: "custom"
          customCommand: "install -g @angular/cli"

- stage: Prepare
#Prepare the sonar cloud
  jobs:
    - job: Prepare
      displayName: 'Prepare analysis configuration'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'P2 Scanner'
          organization: '210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: '210726-wvu-net-ext_Group3-P2'
          projectName: 'Group3-P2'
          extraProperties: 'sonar.exclusions=**/lib/**/*'

- stage: Builds
  #Building and Testing
  jobs:
  # Angular Build and Test Here
    - job: NGBuild 
      displayName: Angular Build/Test
      steps:
      #Restore
      - task: Npm@1
        displayName: Restore NPM
        inputs:
          command: "custom"
          customCommand: 'npm ci'
      #Build
      - task: CmdLine@2
        displayName: Angular Build
        inputs:
          script: 'npx ng build'
          workingDirectory: $(angular)
      #Check
      # - task: CmdLine@2
      #   displayName: Check Angular Violations
      #   inputs:
      #     script: 'npx ng lint'
      #     workingDirectory: $(angular)
      # #Test
      - task: CmdLine@2
        displayName: Angular Tests
        inputs:
          script: 'npx ng test --browsers=ChromeHeadless --code-coverage --watch=false'
          workingDirectory: $(angular)


  # DotNet Build and Test Here
    - job: DNBuild
      displayName: Dotnet Build/Test
      steps:
      # Force dotnet 5 again
      - task: UseDotNet@2
        displayName: Dotnet SDK 5
        inputs:
          packageType: 'sdk'
          version: '5.x'
      #Build
      - task: CmdLine@2
        displayName: Dotnet Build
        inputs:
          script: 'dotnet build --configuration Release'
          workingDirectory: $(sDir)
      #Test
      - task: CmdLine@2
        displayName: Dotnet Tests
        inputs:
          script: 'dotnet test --configuration Release'
          workingDirectory: $(sDir)


- stage: Final
  #Performs the Sonar Analyze and publish results
  jobs:
    - job: Analyze
      steps:
      - task: SonarCloudAnalyze@1
        displayName: 'Run SonarCloud analysis'
    - job: Publish
      steps:
      - task: SonarCloudPublish@1
        displayName: 'Publish results on build summary'