#ANGULAR LINT NOT FULLY IMPLEMENTED YET
trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  angular: '$(Build.SourcesDirectory)/Trader-app'

stages: 
- stage: Installs
  #Runs NPM Installs
  jobs:
    - job: npmInstall
      displayName: NPM Install
      steps:
      #Install Node
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
            versionSpec: 14.x

- stage: Angular_BT
  jobs:
  # Angular Build and Test Here
    - job: NGBuild 
      displayName: Angular Build/Test
      steps:
      #Restore
      - task: Npm@1
        displayName: Restore NPM
        inputs:
          command: 'ci'
          workingDir: '$(angular)'
      #Build
      - task: CmdLine@2
        displayName: Angular Build
        inputs:
          script: 'npx ng build'
          workingDirectory: $(angular)
      #Check
      # - task: CmdLine@2
      #   displayName: Check Angular Violations
      #   inputs:
      #     script: 'npx ng lint'
      #     workingDirectory: $(angular)
      # #Test
      - task: CmdLine@2
        displayName: Angular Tests
        inputs:
          script: 'npx ng test --browsers=ChromeHeadless --code-coverage --watch=false'
          workingDirectory: $(angular)
