#ANGULAR BUILD NOT WORKING YET
trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  sDir: 'P2-Store'
  solution: 'P2-Store/*.sln'
  angular: 'Trader-app'

stages: 
- stage: Restores_Installs
  #Runs NuGet and NPM restores
  jobs:
    - job: NuRestore
      displayName: NuGet Restore
      steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(solution)
    - job: npmRestore
      displayName: NPM Restore
      steps:
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
            versionSpec: 14.x
      - task: Npm@1
        displayName: Install Angular
        inputs:
          command: "custom"
          customCommand: "install -g @angular/cli"

      - task: Npm@1
        displayName: "Install_Restore npm packages"
        inputs:
          command: "install"

- stage: Prepare
#Prepare the sonar cloud
  jobs:
    - job: Prepare
      displayName: 'Prepare analysis configuration'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'P2 Scanner'
          organization: '210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: '210726-wvu-net-ext_Group3-P2'
          projectName: 'Group3-P2'
          extraProperties: 'sonar.exclusions=**/lib/**/*'

- stage: Builds
  #Building and Testing
  jobs:
  # Angular Build and Test Here
    - job: NGBuild 
      displayName: Angular Build/Test
      steps:
      - task: CmdLine@2
        displayName: Angular Build
        inputs:
          script: 'ng build --prod'
          workingDirectory: $(angular)
      - task: CmdLine@2
        displayName: Check Angular Violations
        inputs:
          script: 'ng lint'
          workingDirectory: $(angular)
      - task: CmdLine@2
        displayName: Angular Tests
        inputs:
          script: 'ng test --browsers=ChromeHeadless --code-coverage --watch=false'
          workingDirectory: $(angular)


  # DotNet Build and Test Here
    - job: DNBuild
      displayName: Dotnet Build/Test
      steps:
      # Force dotnet 5
      - task: UseDotNet@2
        displayName: Dotnet SDK 5
        inputs:
          packageType: 'sdk'
          version: '5.x'
      - task: CmdLine@2
        displayName: Dotnet Build
        inputs:
          script: 'dotnet build --configuration Release'
          workingDirectory: $(sDir)
      - task: CmdLine@2
        displayName: Dotnet Tests
        inputs:
          script: 'dotnet test --configuration Release'
          workingDirectory: $(sDir)


- stage: Final
  #Performs the Sonar Analyze and publish results
  jobs:
    - job: Analyze
      steps:
      - task: SonarCloudAnalyze@1
        displayName: 'Run SonarCloud analysis'
    - job: Publish
      steps:
      - task: SonarCloudPublish@1
        displayName: 'Publish results on build summary'